language: scala
jdk:
  - openjdk8

script:
  - ./scripts/cibuild

deploy:
  provider: releases
  api_key:
    secure: sTok7HfQeuzXOQBEjskTQ7aFx3lzk/NLIZ63BZtrUpkIAYk06opbYcINOPD+2lrSOLTHAhgBje2DykWZ4szcNSuSSFZ7oCCY3J/UgvGB1khoeufm876z03ChN6tlVvYokoL6zDHr3BM9vOW+6se0ww0ECxLn1dixQraOvQOhRRHlGhh39Lzf/1r7llN39kqOVEII1C2ju8bMdaql9CGLmIz2gAzQQEN2uH3PO0RRow4Uzo7c1YbQSeZbPo5zwyFKXvRgGpzEICoDygS64QV5TXnBWJEy+w9LfnS39kbVGp0ysHuPTbh2eDIEP7Y+JdPtXAB6YMy4TwEkq2919/uP4Xq+jQGg//lUdyji0eFvg+ZfGMQHcJYOhMWVtrIPlRBhnRSScSPS9sj3LMwkIGWdRZ3PAaV8DzhwNJxdGpTeJ8oBOBFiE18v5ygs8k9J79silDP6ZQaBQT+9lkKQS8NhJIm5GOKm4l6oBereNSF91zIcmZfL6yPrEoznHM50KO1B/MToOsa5cHOrdRQqJaxIJt72RxRmecPERwBcPEXybrf8edkGxiNt0EZL/xuEW1NAvXuQJkz5+Jxdf0l0zDnXPVWXOrmA1ICA/tg6U+nKU/ZyLmR87UwRwXCqwgef7zYe0VhBxB1nrtXkNSMnnwFiPxDmfKPtMqviDSVpBop/bYw=
  file:
    - api/target/scala-2.11/api-assembly-${TRAVIS_TAG}.jar
  skip_cleanup: true
  on:
    repo: WikiWatershed/mmw-geoprocessing
    tags: true
