name: CI

on:
  push:
    branches:
      - develop
      - hotfix/**
      - release/**
      - test/**
  pull_request:
  workflow_dispatch:

jobs:
  compile-then-run-tests:
    name: Compile scala then run server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install and configure pipenv
        run: |
          PYTHON_PATH=$(which python)
          pip install pipenv
          pipenv --python $PYTHON_PATH
        
      - name: Run setup script
        run: ./scripts/setup

      - name: Run server
        run: |
          ./scripts/server >/dev/null 2>&1 &
          echo "SERVER_PID=$!" >> "$GITHUB_ENV"

      # - name: Run test script
      #   run: |
      #     sleep 15
      #     curl localhost:8090/pong

      - name: Stop server
        run: |
          echo $SERVER_PID
      #     kill $SERVER_PID

