name: CI

on:
  push:
    branches:
      - develop
      - hotfix/**
      - release/**
      - test/**
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    name: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install and configure pipenv
        run: |
          python --version
          PYTHON_PATH=$(which python)
          pip --version
          pip install pipenv
          pipenv --python $PYTHON_PATH
        
      - name: Run setup
        run: ./scripts/setup

