name: CI

on:
  push:
    branches:
      - develop
      - hotfix/**
      - release/**
      - test/**
  pull_request:
  workflow_dispatch:

jobs:
  compile-then-run-tests:
    name: Compile scala, run server, run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
    
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install and configure pipenv
        run: |
          PYTHON_PATH=$(which python)
          pip install pipenv
          pipenv --python $PYTHON_PATH
        
      - name: Run setup script
        run: ./scripts/setup

      - name: Run test
        run: ./scripts/citest
